server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: info,health,metrics,loggers,beans,mappings,threaddump,env,caches
  endpoint:
    health:
      show-details: always
spring:
  jpa:
    show-sql: true
    datasource:
      url: jdbc:mysql://localhost:3306/bankingDB
      username: root
      password: Tanvi@2808
      driver-class-name: com.mysql.cj.jdbc.Driver