server:
    port: 9091
logging:
    level:
        com.spring.reporting: DEBUG
    filename : spring-spring-app-log-file.log
    pattern:
        file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
        console: "%d %-5level %logger : %msg%n"
bank:
    url: http://localhost:9090/api/v1/banks
